import Steve from '@shell/plugins/steve/steve-class.js';
import { steveClassJunkObject } from './utils/steve-mocks';

describe('class: Steve', () => {
  describe('given custom resource keys', () => {
    const customResource = steveClassJunkObject;

    it('should keep internal keys', () => {
      const steve = new Steve(customResource, {
        getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
        dispatch:    jest.fn(),
        rootGetters: { 'i18n/t': jest.fn() },
      });

      expect({ ...steve }).toStrictEqual(customResource);
    });

    describe('method: save', () => {
      it('should remove all the internal keys', async() => {
        const dispatch = jest.fn();
        const steve = new Steve(customResource, {
          getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
          dispatch,
          rootGetters: { 'i18n/t': jest.fn() },
        });

        const expectation = {
          type:     customResource.type,
          metadata: {
            resourceVersion:            'whatever',
            fields:                     'whatever',
            clusterName:                'whatever',
            deletionGracePeriodSeconds: 'whatever',
            generateName:               'whatever',
            ownerReferences:            'whatever',
          },
          spec: { versions: {} }
        };

        await steve.save();

        const opt = {
          data:    expectation,
          headers: {
            accept:         'application/json',
            'content-type': 'application/json',
          },
          method: 'post',
          url:    undefined,
        };

        // Data sent should have been cleaned
        expect(dispatch).toHaveBeenCalledWith('request', { opt, type: customResource.type });

        // Original workload model should remain unchanged
        expect({ ...steve }).toStrictEqual(customResource);
      });
    });

    describe('method: notifyGeneratedName', () => {
      const createSteve = (value: any) => {
        const dispatch = jest.fn();
        const t = jest.fn((key, params) => `${ key } ${ JSON.stringify(params) }`);
        const steve = new Steve({ ...customResource, ...value }, {
          getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
          dispatch,
          rootGetters: { 'i18n/t': t },
        });

        Object.defineProperty(steve, 'typeDisplay', { get: () => 'CustomResourceDefinition' });

        return {
          steve, dispatch, t
        };
      };

      it.each([
        ['a namespaced resource', 'default/test-generated-abc123', 'test-generated-abc123'],
        ['a cluster scoped resource', 'simple-id', 'simple-id'],
      ])('should show the growl with the generated name for %p', (_, id, expectedId) => {
        const { steve, dispatch, t } = createSteve({ id, metadata: { generateName: 'test-generated-' } });

        steve.notifyGeneratedName();

        expect(t).toHaveBeenCalledWith('generic.autogeneratedCreated.title', { resource: 'CustomResourceDefinition' });
        expect(t).toHaveBeenCalledWith('generic.autogeneratedCreated.message', { id: expectedId, resource: 'CustomResourceDefinition' });
        expect(dispatch).toHaveBeenCalledWith('growl/success', {
          title:   `generic.autogeneratedCreated.title ${ JSON.stringify({ resource: 'CustomResourceDefinition' }) }`,
          message: `generic.autogeneratedCreated.message ${ JSON.stringify({ id: expectedId, resource: 'CustomResourceDefinition' }) }`,
          timeout: 3000
        }, { root: true });
      });

      it.each([
        ['without generateName', { id: 'default/test-regular-name', metadata: { name: 'test-regular-name' } }],
        ['without id', { id: undefined, metadata: { generateName: 'test-generated-' } }],
      ])('should not show the growl %s', (_, value) => {
        const { steve, dispatch } = createSteve(value);

        steve.notifyGeneratedName();

        expect(dispatch).toHaveBeenCalledTimes(0);
      });
    });
  });

  describe('method: fetchOwnedRelatedResources', () => {
    // a Deployment owning one ReplicaSet, in a store where the user can get ReplicaSets
    const owner = (dispatch: jest.Mock) => new Steve({
      type:     'apps.deployment',
      id:       'ns/web',
      metadata: {
        name:          'web',
        namespace:     'ns',
        relationships: [{
          rel: 'owner', toType: 'apps.replicaset', toId: 'ns/web-1'
        }]
      },
    }, {
      getters: {
        schemaFor: () => ({ resourceMethods: ['GET'] }),
        byId:      () => undefined,
      },
      dispatch,
      rootGetters: { 'i18n/t': jest.fn() },
    });

    // steve's relationships do not say whether the owner is the controller, the editor reads that from the resource
    it('should return an owned resource as a dependent, without `readOnly`', async() => {
      const replicaSet = {
        type: 'apps.replicaset', id: 'ns/web-1', typeDisplay: 'ReplicaSet'
      };
      const dispatch = jest.fn(() => Promise.resolve(replicaSet));

      expect(await owner(dispatch).fetchOwnedRelatedResources()).toStrictEqual([{
        resource: replicaSet, group: 'ReplicaSet', dependent: true
      }]);
    });

    // a schema's resourceMethods cover every namespace, so a type the user can get can still be forbidden in one namespace
    it.each([
      ['does not exist', 404],
      ['is forbidden in its namespace', 403],
    ])('should leave out, without a warning, an owned resource that %s', async(_label, status) => {
      const warn = jest.spyOn(console, 'warn').mockImplementation(() => {});
      const dispatch = jest.fn(() => Promise.reject({ _status: status })); // eslint-disable-line prefer-promise-reject-errors

      expect(await owner(dispatch).fetchOwnedRelatedResources()).toStrictEqual([]);
      expect(dispatch).toHaveBeenCalledWith('find', {
        type: 'apps.replicaset', id: 'ns/web-1', opt: { watch: false }
      });
      expect(warn).toHaveBeenCalledTimes(0);

      warn.mockRestore();
    });

    it('should leave out, with a warning, an owned resource whose request fails for another reason', async() => {
      const warn = jest.spyOn(console, 'warn').mockImplementation(() => {});
      const error = { _status: 500 };
      const dispatch = jest.fn(() => Promise.reject(error));

      expect(await owner(dispatch).fetchOwnedRelatedResources()).toStrictEqual([]);
      expect(warn).toHaveBeenCalledWith('Failed to fetch apps.replicaset ns/web-1', error);

      warn.mockRestore();
    });
  });
});
